//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.25 at 03:50:58 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pigrick.com/springbootggbackend/xml/game", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.pigrick.springbootggfrontend.wsdl;
